// SPDX-License-Identifier: BSD-3-Clause
// SPDX-FileCopyrightText: 2025-2026 Harald Sitter <sitter@kde.org>

package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	"github.com/coreos/go-systemd/unit"
)

func pathFromUrl(url string) (string, error) {
	if !strings.HasPrefix(url, "http://") && !strings.HasPrefix(url, "https://") {
		return "", fmt.Errorf("invalid URL format: %s", url)
	}

	parts := strings.SplitN(url, "/", 4)
	if len(parts) < 4 {
		return "", fmt.Errorf("invalid URL format: %s", url)
	}

	return "/" + parts[3], nil
}

func pathFromTransferFile(filePath string) (string, error) {
	if _, err := os.Stat(filePath); err != nil {
		return "", fmt.Errorf("failed to stat file: %w", err)
	}

	file, err := os.Open(filePath)
	if err != nil {
		return "", fmt.Errorf("failed to open file: %w", err)
	}
	defer file.Close()

	options, err := unit.Deserialize(file)
	if err != nil {
		return "", fmt.Errorf("failed to deserialize unit file: %w", err)
	}

	var path *string = nil
	for _, option := range options {
		if option.Section == "Source" && option.Name == "Path" {
			p, err := pathFromUrl(option.Value)
			if err != nil {
				return "", fmt.Errorf("failed to get path from URL: %w", err)
			}
			path = &p
			break
		}
	}
	if path == nil {
		return "", fmt.Errorf("no Source Path found in %s", filePath)
	}

	return *path, nil
}

func main() {
	path, err := pathFromTransferFile("/usr/lib/sysupdate.d/50-root-x86-64-erofs.transfer")
	if err != nil {
		log.Fatalln("Failed to get path from transfer file:", err)
	}

	fmt.Println("Original Source Path:", path)
	newPath := "http://localhost:3129" + path
	fmt.Println("New Source Path:", newPath)

	newOption := unit.NewUnitOption("Source", "Path", newPath)

	overrideDir := "/run/sysupdate.d/50-root-x86-64-erofs.transfer.d"
	os.MkdirAll(overrideDir, 0755)

	outFile, err := os.Create(overrideDir + "/00-default.conf")
	if err != nil {
		log.Fatalln("Failed to create override file:", err)
	}
	defer outFile.Close()

	outFile.Write([]byte("# This file was automatically generated by kde-linux-sysupdated-redirector\n"))
	_, err = io.Copy(outFile, unit.Serialize([]*unit.UnitOption{newOption}))
	if err != nil {
		log.Fatalln("Failed to write override file:", err)
	}
	fmt.Println("Override file created at", outFile.Name())
}
